branches:
  - main
  - name: develop
    prerelease: true
debug: true
ci: true
dryRun: false
tagFormat: '${version}'
plugins:
  - "@semantic-release/changelog"
    changelogFile: docs/CHANGELOG.md
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
