# .github/workflows/release-develop.yaml
name: "Release New Development Version"

on:
  push:
    branches:
      - 'develop'

jobs:
  update-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Configure committer
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Bump version
      uses: qzb/standard-version-action@v1.0.5
  