# .github/workflows/release-develop.yaml
name: "Release Development Version"

on:
  push:
    tags:
      - 'v*.*.*-*.*'

jobs:
  get-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: package.json info
      id: info
      uses: jaywcjlove/github-action-package@main
    - run: echo "version - ${{ steps.info.outputs.version }}"
