# .github/workflows/release-develop.yaml
name: "Release Development Version"

on:
  push:
    branches: [ main, develop ]

jobs:
  get-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: package.json info
      id: info
      uses: actions/checkout@v3
    - run: echo "${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}"
