# .github/workflows/release-develop.yaml
name: "Release New Development Version"

on:
  push:
    branches:
      - 'develop'

jobs:
  update-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        git config --global user.name "<GITHUB BOT>"
        git config --global user.email "<>"
        npx standard-version
        git push --follow-tags origin develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  