# .github/workflows/release-develop.yaml
name: "Release Development Version"

on:
  push:
    branches: [ main, develop ]

jobs:
  get-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: info
      id: branch-info
      uses: actions/checkout@v3
    - run: echo "${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}" # gets branch
    - name: package.json info
      id: package-info
      uses: jaywcjlove/github-action-package@main

    - run: echo "name - ${{ steps.package-info.outputs.name }}"
    - run: echo "version - ${{ steps.package-info.outputs.version }}"
    - run: echo "description - ${{ steps.package-info.outputs.description }}"
    - run: echo "author - ${{ steps.package-info.outputs.author }}"